language: node_js
node_js: '12'
jobs:
  include:
    - stage: test
      script:
        - jest --clearCache
        - lerna bootstrap
        - npm run build
        - npm run test:coverage
        - npm run report:coverage